### ISSUE TITLE
Error when using grunt to start up the project

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb-public#111]
/Users/jiaojiao/repos/oncokb-public/app/scripts/services/markedSwagger.js
  12:9  error  Unexpected 'this'  no-invalid-this

Running "karma:unit" (karma) task
12 06 2017 11:07:27.548:ERROR [config]: File /Users/jiaojiao/repos/oncokb-public/test/karma.conf.js does not exist!

**Comment by zhx828** [comment]
Related to node versions. And also related to cached node_modules between version changes.

https://github.com/remy/nodemon/issues/1124
