### ISSUE TITLE
API for MUTATION_SUMMARY Evidence access is incorrect

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb-public#120]
http://oncokb.org/api/v1/evidences/lookup?entrezGeneId=673&hugoSymbol=BRAF&variant=V600E&source=oncotree&evidenceTypes=MUTATION_SUMMARY

We don't curate MUTAION_SUMMARY evidence any more, need to adjust that in the exposed api.

**Comment by zhx828** [comment]
@JiaoJiao123 we still use MUTATION_SUMMARY emphasizing the oncogenicity summary.
