### ISSUE TITLE
return general mutations themselves when querying their relevant alterations

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb-public#132]
In the api whose end point is "variants/lookup", general mutation itself, for example Oncogenic Mutations, is not returned when query for the relevant alterations of "Oncogenic Mutations" in BRCA1. That general mutation should be returned among the relevant alteration list when it is a real mutation for the query gene.

**Comment by zhx828** [comment]
Issue has been solved in https://github.com/oncokb/oncokb/pull/698
