### ISSUE TITLE
Variant page does not show highest level from relevant variants

### ISSUE THREAD

**Issue by zhx828** [oncokb/oncokb-public#136]
BRCA1 Y1853* is supposed to be level 1, it shows as level 1 in search result but not in variant page.
<img width="813" alt="screen shot 2017-08-04 at 7 49 35 am" src="https://user-images.githubusercontent.com/5400599/28969292-9fe7747c-78e9-11e7-9c17-fa547296cd2f.png">
<img width="1198" alt="screen shot 2017-08-04 at 7 49 27 am" src="https://user-images.githubusercontent.com/5400599/28969297-a5978e98-78e9-11e7-8de4-0b2720790728.png">

**Comment by JiaoJiao123** [comment]
@zhx828 Currently, the level we display is exactly the level of query variant. Just want to confirm, we should pick the highest level from all its relevant alterations right?

**Comment by JiaoJiao123** [comment]
@zhx828 I checked with JJ, and we should use the highest level among all relevant variants. And this issue is fixed in PR #137
