### ISSUE TITLE
Some data in the mutation mapper have no mapping record in the table

### ISSUE THREAD

**Issue by JiaoJiao123** [oncokb/oncokb-public#76]
http://oncokb.org/#/gene/BRCA2
In the mutation lollipop, click on L1491Kfs*12, and the mutation table updates but shows zero rows.  But, if you go to this MSK sample in GENIE:  http://www.cbioportal.org/genie/case.do?cancer_study_id=genie_public&sample_id=GENIE-MSK-P-0000597-T01-IM3, you can see that BRCA2 L1491Kfs*12 is listed as tier 2 in OncoKB.

Solutions: L1491Kfs*12 should be linked to truncating mutations and Oncogenenic mutations. We need to implement some logic in the frontend to link to generic mutation entries. Similar rules should be set for other type of variants like DNA binding domain missense mutations, DNA binding domain insertions/deletions.

**Comment by zhx828** [comment]
@JiaoJiao123 is this fixed?

**Comment by JiaoJiao123** [comment]
The data was corrupted because of a bug in the portal alteration importer, which has been fixed
