### ISSUE TITLE
Replace usage terms with an open license to allow data reuse

### ISSUE THREAD

**Issue by dhimmel** [oncokb/oncokb-public#95]
Greetings, I help lead an open source cancer research project and meetup called Cognoma. We recently became interested in using the [OncoKB data](http://oncokb.org/#/dataAccess): see https://github.com/cognoma/machine-learning/issues/88.

Unfortunately, the current website terms at http://oncokb.org/#/terms ([source](https://github.com/oncokb/oncokb-public/blob/6b3d2f982744b7612eba5536752f1429dc2eed32/app/views/license.html#L25-L28)) state:

> You may view the content contained on http://oncokb.org solely for your own personal or research purposes. You may not copy, transfer, reproduce, modify, or create derivative works of any part of the http://oncokb.org content for any reason and you may not distribute, license or sell the content, alone or in combination with other materials, to any other person or entity, without the express written permission of MSK.

Unfortunately, the ability to copy, transfer, reproduce, modify, and create derivative works is essential for research. For example, almost any use case of the TSV downloads requires copying. The ability to transfer and reproduce data is essential for reproducibility. Currently, the usage terms imply users cannot even upload the datasets to GitHub as part of an analysis. Finally, Cognoma, which must be entirely open and publicly available since it's a volunteer meetup, would like to build on the datasets for research. For this, we'll need to modify the downloads and create derivative works.

It's questionable whether the usage terms even are legally binding, since the datasets may not be subject to copyright in the United States and users don't actually have to agree to these terms to download the datasets. But for conservative users, the current OncoKB usage terms make the data unusable for research. I assume this is not the intent of the OncoKB creators, as you've gone to great lengths to make a nice interface with data available!

The solution is to apply an [open license](http://opendefinition.org/licenses/) to the datasets. I'm happy to provide more advice on how to improve the situation. I'd hate to see such a valuable resource go to waste due to unfortunate usage terms.

**Comment by dhimmel** [comment]
Tagging contributors who modified the terms/license in the past:

+ @JiaoJiao123 in https://github.com/oncokb/oncokb-public/commit/dba74f64dbf212957c6ba8f2215474178ae98675
+ @zhx828 in https://github.com/oncokb/oncokb-public/commit/f7fd988b7f4297c0d727a53b3b5a41234df29f5d

Wanted to check in whether you're considering adopting an open license? We're still interested in using OncoKB, but do not want to proceed until the license permits open reuse.

**Comment by zhx828** [comment]
@dhimmel Sorry, I forgot to update you here. We updated our usage terms http://oncokb.org/#/terms couple days ago. Please check the new terms whether it works for you. But this is the final decision from the legal department. Hope this helps.

**Comment by dhimmel** [comment]
Thanks @zhx828 for following up, and I know these changes can take a lot of energy on your part. I see the terms were updated in https://github.com/oncokb/oncokb-public/commit/a3c4f354635312ce52e2544fe5800eb0381bdcba. For reference, the new terms read:

![oncokb-terms](https://cloud.githubusercontent.com/assets/1117703/26602752/7c344f66-4552-11e7-8727-61a7bc4e4c96.png)

> Please check the new terms whether it works for you.

The new license allows _certain_ users to engage in reproducible research that uses OncoKB. It potentially allows integrating the data with other resources for cancer research only. Unfortunately, it is not an open license. Furthermore, it is not a standard license and is broadly incompatible with other licenses.

We will consider whether this data is subject to copyright, the potential for fair use, and whether the usage terms are legally binding. But since we're not lawyers and don't want to put ourselves at risk, most likely we will just forego using OncoKB. 

> But this is the final decision from the legal department.

It's disappointing to see legal departments cause obstacles for medical research. Sorry for your situation… I would be quite furious with my university if they used legal tactics to diminish the impact of my research.

**Comment by schultzn** [comment]
Hi Daniel. You can read more about our reasons for the license terms here: https://www.mskcc.org/ibm-watson-and-quest-diagnostics-launch-genomic-sequencing-service-using-data-msk

We are happy that we were able to make the data as open as it is. Under the current terms, the data can be used and re-distributed for research use (for example, it is integrated in the UCSC Genome Browser), and bulk download is also available. 

I am all for open data and science (see cBioPortal, GENIE, MSK-IMPACT manuscript in Nature Medicine), but at the moment, this is as open as possible for OncoKB at the moment. I hope this will change in the future.

I don't see why your project should not be able to use OncoKB given the current license terms.

**Comment by dhimmel** [comment]
Thanks @schultzn for your response and the additional information. I am glad you appreciate the importance of open data. From the [press release](https://www.mskcc.org/ibm-watson-and-quest-diagnostics-launch-genomic-sequencing-service-using-data-msk) you mention, I assume OncoKB's funding comes from a private partnership and that partnership may place restrictions on the data's licensing. Previously, I was under the impression that MSKCC had unnecessarily restricted reuse as I've seen other [Universities do with publicly funded software](http://blog.dhimmel.com/continuous-analysis/). Of course, if OncoKB is privately funded, then I respect the creators' rights to license the resource however they wish.

> I don't see why your project should not be able to use OncoKB given the current license terms.

We've committed to openly licensing the entirety of Project Cognoma. We have to be careful not to include resources that will prohibit us from openly licensing the entire project. For example, we want anyone to be able to reuse Cognoma for any purpose. As a volunteer project, we feel strongly that our research should be made widely reusable by anyone who would like to reuse it. Nonetheless, we will keep OncoKB in mind and determine what reuse we are comfortable with based on the current license. Especially since it's a really awesome and user-friendly resource.

> Under the current terms, the data can be used and re-distributed for research use (for example, it is integrated in the UCSC Genome Browser), and bulk download is also available.

I am worried about large integrative resources such as the UCSC Genome Browser that do not ensure they only integrate openly licensed content. By accepting OncoKB (assuming you haven't given them a special licensing arrangement), the UCSC Genome Browser "poisons the well." Eventually the bioinformatics community will realize core infrastructure like UCSC Genome Browser needs to be openly licensed. The more non-open resources UCSC includes, the harder that task will be. The more likely it will be that the UCSC Genome Browser is obsoleted by a wholly new open alternative. Anyways this is getting a bit off topic... oops!

> I hope this will change in the future.

Okay I will leave this issue open. But feel free to close it as you see fit.

**Comment by schultzn** [comment]
Thanks for understanding @dhimmel. We will try our best, but this issue will likely be open for a while. I understand the complications this causes for anyone who is trying to package our data with their product.

**Comment by zhx828** [comment]
We recently updated our Terms of Use. Please see the [updated terms](https://www.oncokb.org/terms) for more information. There will be no fee for academic research. For any other purposes, please visit the [Data Access Page](https://www.oncokb.org/dataAccess) for more information. Thanks.
